import { Inter, Roboto, Poppins } from "next/font/google";
import Navbar from '@/components/navbar/page'
import Footer from '@/components/footer/page'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <div className="container">
      <Navbar/>
      <body className={inter.className}>{children}</body>
      <Footer/>
      </div>
    </html>
  )
}
